### ISSUE TITLE
Server error when a component with "voting" options (eg budget) does not have at least one check option checked

### ISSUE THREAD

**Issue by aramollis** [CodiTramuntana/decidim-verify_wo_registration#12]
### The bug
When any component with "voting" options does not have at least one verification option checked, it causes a server error that prevents access to said component by non-logged-in users.

### To Reproduce
Steps to reproduce the behaviour:
1. Configure any component (budget e.g.) that requires to be verified to perform some action (vote e.g., ...) and leave unchecked all the options
![image](https://user-images.githubusercontent.com/109797/188666618-8e842ac9-b83e-49f7-bd19-8b4780b1bdb7.png)
3. Sign out
4. Try to access to this component page
5. Error

### Expected behaviour
When any component with "voting" options does not have at least one verification option checked, then verification should not be required and it is not possible to perform the action without being logged in.

**Comment by tramuntanal** [comment]
Fixed in #13
