### ISSUE TITLE
Improve the way text is displayed in the login modal window

### ISSUE THREAD

**Issue by aramollis** [CodiTramuntana/decidim-verify_wo_registration#8]
A customer you installed this  [decidim-verify_wo_registration] module for in the past, wants to change the text from the actual custom modal window shown when not authenticated user try to perform an action that requires verification. 

- [ ] Add heading: No tinc compte i no em vull registrar
- [ ] Change text button to: Verifica't sense registre
- [ ] Change right heading: Ja tinc un compte. Inicia la sessió i verifica't

(https://github.com/CodiTramuntana/decidim-verify_wo_registration) module
![178270064-1717aebd-2503-4d37-9eee-106cd125d033](https://user-images.githubusercontent.com/109797/179458698-4fe13b89-710a-45ea-874f-f8117e1915aa.png)

Can you approve this change? Then we will prepare a PR. 

Tx!

**Comment by tramuntanal** [comment]
Resolved by https://github.com/CodiTramuntana/decidim-verify_wo_registration/pull/11
